### ISSUE TITLE
Question: Will this ensure that all the connections of the machine are sent through vpn?

### ISSUE THREAD

**Issue by amilajack** [luigiplr/node-openvpn#5]

**Comment by luigiplr** [comment]
It should yes, please see https://github.com/luigiplr/node-openvpn/issues/4#issuecomment-239268272 for a up to date example on how to use it.

**Comment by amilajack** [comment]
I see. What if the machine that the module is running on doesn't have openvpn?

**Comment by luigiplr** [comment]
Expect fire.

If your planning on using this inside of a electron app, i would recommend simply bundling the platform specific openvpn executable.

**Comment by amilajack** [comment]
So it wont work without bundling the native libraries?

**Comment by luigiplr** [comment]
Correct.
